{% set name = "pyauthenticator" %}
{% set version = "0.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyauthenticator-{{ version }}.tar.gz
  sha256: 481f08b69b9d09ad15b052ac73b104b801ee8021eea49c92d06832e53c186950

build:
  number: 0
  noarch: python
  entry_points:
    - pyauthenticator=pyauthenticator.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - otpauth
    - pillow
    - python >=3.6
    - pyzbar
    - qrcode
    - zbar

test:
  imports:
    - pyauthenticator
  commands:
    - pip check
    - pyauthenticator --help
  requires:
    - pip

about:
  home: https://github.com/jan-janssen/pyauthenticator
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Similar to the Google authenticator just written in Python.'
  description: |
    Similar to the Google authenticator just written in Python. With more 
    and more services requiring two factor authentication without 
    supporting application specific passwords or other forms of token 
    based authenication suitable for automation this python packages 
    allows to generate two factor authentication codes on the commandline
    or in python.
  doc_url: https://github.com/jan-janssen/pyauthenticator
  dev_url: https://github.com/jan-janssen/pyauthenticator

extra:
  recipe-maintainers:
    - jan-janssen
