{% set name = "pyauthenticator" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyauthenticator-{{ version }}.tar.gz
  sha256: 1efa76acbbc124950501d2e812fb9f84d28be9c4ec1cb0a4f323a0006b7464f5

build:
  number: 0
  noarch: python
  entry_points:
    - pyauthenticator=pyauthenticator.__main__:command_line_parser
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - pyotp >=2.6.0
    - pillow >=9.5.0
    - python >=3.8
    - pyzbar >=0.1.9
    - qrcode >=7.4.2
    - zbar >=0.10

test:
  imports:
    - pyauthenticator
  commands:
    - pip check
    - pyauthenticator --help
  requires:
    - pip

about:
  home: https://github.com/jan-janssen/pyauthenticator
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Similar to the Google authenticator just written in Python.'
  description: |
    Similar to the Google authenticator just written in Python. With more 
    and more services requiring two factor authentication without 
    supporting application specific passwords or other forms of token 
    based authenication suitable for automation this python packages 
    allows to generate two factor authentication codes on the commandline
    or in python.
  doc_url: https://github.com/jan-janssen/pyauthenticator
  dev_url: https://github.com/jan-janssen/pyauthenticator

extra:
  recipe-maintainers:
    - jan-janssen
