{% set name = "pyauthenticator" %}
{% set version = "0.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyauthenticator-{{ version }}.tar.gz
  sha256: 97a35933f652bf717d0d56ff28eb419b7901ec94af2108b6b8cc168a88f84893

build:
  number: 0
  noarch: python
  entry_points:
    - pyauthenticator=pyauthenticator.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - otpauth >=1.0.1
    - pillow >=8.1.2
    - python >=3.6
    - pyzbar >=0.1.8
    - qrcode >=6.1
    - zbar >=0.10

test:
  imports:
    - pyauthenticator
  commands:
    - pip check
    - pyauthenticator --help
  requires:
    - pip

about:
  home: https://github.com/jan-janssen/pyauthenticator
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Similar to the Google authenticator just written in Python.'
  description: |
    Similar to the Google authenticator just written in Python. With more 
    and more services requiring two factor authentication without 
    supporting application specific passwords or other forms of token 
    based authenication suitable for automation this python packages 
    allows to generate two factor authentication codes on the commandline
    or in python.
  doc_url: https://github.com/jan-janssen/pyauthenticator
  dev_url: https://github.com/jan-janssen/pyauthenticator

extra:
  recipe-maintainers:
    - jan-janssen
