{% set name = "pyauthenticator" %}
{% set version = "0.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyauthenticator-{{ version }}.tar.gz
  sha256: 778fe27f520212b6808292dbb924edb3e5d2c2f0be646a799dd7e060852d1c93

build:
  number: 0
  noarch: python
  entry_points:
    - pyauthenticator=pyauthenticator.cmd:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - otpauth
    - pillow
    - python >=3.6
    - pyzbar
    - qrcode

test:
  imports:
    - pyauthenticator
  commands:
    - pip check
    - pyauthenticator --help
  requires:
    - pip

about:
  home: https://github.com/jan-janssen/pyauthenticator
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Similar to the Google authenticator just written in Python.'
  description: |
    Similar to the Google authenticator just written in Python. With more 
    and more services requiring two factor authentication without 
    supporting application specific passwords or other forms of token 
    based authenication suitable for automation this python packages 
    allows to generate two factor authentication codes on the commandline
    or in python.
  doc_url: https://github.com/jan-janssen/pyauthenticator
  dev_url: https://github.com/jan-janssen/pyauthenticator

extra:
  recipe-maintainers:
    - jan-janssen
