{% set name = "pyauthenticator" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyauthenticator-{{ version }}.tar.gz
  sha256: 1efa76acbbc124950501d2e812fb9f84d28be9c4ec1cb0a4f323a0006b7464f5
  patches:
    - versioneer.patch

build:
  entry_points:
    - pyauthenticator=pyauthenticator.__main__:command_line_parser
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - pyotp >=2.6.0
    - qrcode >=7.4.2
    - pyzbar >=0.1.9
    - pillow >=10.0.0

test:
  imports:
    - pyauthenticator
  commands:
    - pip check
    - pyauthenticator --help
  requires:
    - pip

about:
  home: https://github.com/jan-janssen/pyauthenticator
  summary: Similar to the Google authenticator just written in python.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
