{% set name = "pyauthenticator" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyauthenticator-{{ version }}.tar.gz
  sha256: a927a361f785073ba92b1ed6a2029170ec55918252e82381560a2bb26b136e46

build:
  entry_points:
    - pyauthenticator=pyauthenticator.__main__:command_line_parser
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - pyotp >=2.9.0
    - qrcode >=8.2
    - pyzbar >=0.1.9
    - pillow >=11.3.0

test:
  imports:
    - pyauthenticator
  commands:
    - pip check
    - pyauthenticator --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jan-janssen/pyauthenticator
  summary: Similar to the Google authenticator just written in python.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
